# Generated by Django 3.1.2 on 2020-11-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201105_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='store.TagModel'),
        ),
    ]
